command: ['streamlit', 'run', 'app.py']
env:
  - name: 'DATABRICKS_WAREHOUSE_ID'
    valueFrom: "sql-warehouse"
  - name: 'STREAMLIT_GATHER_USAGE_STATS'
    value: 'false'
  - name: 'STREAMLIT_SERVER_HEADLESS'
    value: 'true'
  - name: 'STREAMLIT_SERVER_ENABLE_CORS'
    value: 'false'
  - name: 'UNITY_CATALOG_NAME'
    value: 'quickstart_catalog_vkm_external'
  - name: 'UNITY_SCHEMA_NAME'
    value: 'classify_tickets'
